[2024-09-22T20:01:42.610+0000] {processor.py:186} INFO - Started process (PID=11344) to work on /opt/airflow/dags/new_dag.py
[2024-09-22T20:01:42.614+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/new_dag.py for tasks to queue
[2024-09-22T20:01:42.627+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:01:42.621+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/new_dag.py
[2024-09-22T20:01:42.707+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:01:42.698+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/new_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/new_dag.py", line 8, in <module>
    from test_oop import DataAgregation
ModuleNotFoundError: No module named 'test_oop'
[2024-09-22T20:01:42.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/new_dag.py
[2024-09-22T20:01:42.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/new_dag.py took 0.294 seconds
[2024-09-22T20:01:59.771+0000] {processor.py:186} INFO - Started process (PID=11351) to work on /opt/airflow/dags/new_dag.py
[2024-09-22T20:01:59.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/new_dag.py for tasks to queue
[2024-09-22T20:01:59.776+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:01:59.775+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/new_dag.py
[2024-09-22T20:01:59.847+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:01:59.830+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/new_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/new_dag.py", line 7, in <module>
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(profile_task), '..')))
                                                                 ^^^^^^^^^^^^
NameError: name 'profile_task' is not defined
[2024-09-22T20:01:59.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/new_dag.py
[2024-09-22T20:01:59.888+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/new_dag.py took 0.131 seconds
[2024-09-22T20:02:30.121+0000] {processor.py:186} INFO - Started process (PID=11358) to work on /opt/airflow/dags/new_dag.py
[2024-09-22T20:02:30.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/new_dag.py for tasks to queue
[2024-09-22T20:02:30.131+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:02:30.130+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/new_dag.py
[2024-09-22T20:02:30.182+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:02:30.153+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/new_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/new_dag.py", line 7, in <module>
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(profile_task), '..')))
                                                                 ^^^^^^^^^^^^
NameError: name 'profile_task' is not defined
[2024-09-22T20:02:30.196+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/new_dag.py
[2024-09-22T20:02:30.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/new_dag.py took 0.128 seconds
[2024-09-22T20:02:57.505+0000] {processor.py:186} INFO - Started process (PID=11365) to work on /opt/airflow/dags/new_dag.py
[2024-09-22T20:02:57.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/new_dag.py for tasks to queue
[2024-09-22T20:02:57.512+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:02:57.512+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/new_dag.py
[2024-09-22T20:02:57.579+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:02:57.568+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/new_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/new_dag.py", line 10, in <module>
    from test_oop import DataAgregation  # Импортируем класс из файла test_oop.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'test_oop'
[2024-09-22T20:02:57.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/new_dag.py
[2024-09-22T20:02:57.615+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/new_dag.py took 0.117 seconds
[2024-09-22T20:03:27.843+0000] {processor.py:186} INFO - Started process (PID=11371) to work on /opt/airflow/dags/new_dag.py
[2024-09-22T20:03:27.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/new_dag.py for tasks to queue
[2024-09-22T20:03:27.850+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:03:27.849+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/new_dag.py
[2024-09-22T20:03:27.876+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:03:27.871+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/new_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/new_dag.py", line 10, in <module>
    from test_oop import DataAgregation  # Импортируем класс из файла test_oop.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'test_oop'
[2024-09-22T20:03:27.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/new_dag.py
[2024-09-22T20:03:27.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/new_dag.py took 0.068 seconds
[2024-09-22T20:03:49.217+0000] {processor.py:186} INFO - Started process (PID=11378) to work on /opt/airflow/dags/new_dag.py
[2024-09-22T20:03:49.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/new_dag.py for tasks to queue
[2024-09-22T20:03:49.221+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:03:49.220+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/new_dag.py
[2024-09-22T20:03:49.287+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:03:49.280+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/new_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/new_dag.py", line 4, in <module>
    from profile_task.test_oop import DataAgregation
ModuleNotFoundError: No module named 'profile_task'
[2024-09-22T20:03:49.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/new_dag.py
[2024-09-22T20:03:49.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/new_dag.py took 0.166 seconds
[2024-09-22T20:04:04.409+0000] {processor.py:186} INFO - Started process (PID=11379) to work on /opt/airflow/dags/new_dag.py
[2024-09-22T20:04:04.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/new_dag.py for tasks to queue
[2024-09-22T20:04:04.413+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:04:04.412+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/new_dag.py
[2024-09-22T20:04:04.448+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:04:04.443+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/new_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/new_dag.py", line 4, in <module>
    from profile_task.test_oop import DataAgregation
ModuleNotFoundError: No module named 'profile_task'
[2024-09-22T20:04:04.450+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/new_dag.py
[2024-09-22T20:04:04.507+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/new_dag.py took 0.107 seconds
[2024-09-22T20:04:20.654+0000] {processor.py:186} INFO - Started process (PID=11386) to work on /opt/airflow/dags/new_dag.py
[2024-09-22T20:04:20.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/new_dag.py for tasks to queue
[2024-09-22T20:04:20.658+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:04:20.657+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/new_dag.py
[2024-09-22T20:04:20.693+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:04:20.689+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/new_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/new_dag.py", line 4, in <module>
    from profile_task.test_oop import DataAgregation
ModuleNotFoundError: No module named 'profile_task'
[2024-09-22T20:04:20.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/new_dag.py
[2024-09-22T20:04:20.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/new_dag.py took 0.113 seconds
[2024-09-22T20:05:45.241+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/new_dag.py
[2024-09-22T20:05:45.246+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/new_dag.py for tasks to queue
[2024-09-22T20:05:45.257+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:05:45.256+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/new_dag.py
[2024-09-22T20:05:45.285+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:05:45.278+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/new_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/new_dag.py", line 4, in <module>
    from profile_task.test_oop import DataAgregation
ModuleNotFoundError: No module named 'profile_task'
[2024-09-22T20:05:45.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/new_dag.py
[2024-09-22T20:05:45.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/new_dag.py took 0.116 seconds
[2024-09-22T20:06:15.685+0000] {processor.py:186} INFO - Started process (PID=41) to work on /opt/airflow/dags/new_dag.py
[2024-09-22T20:06:15.687+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/new_dag.py for tasks to queue
[2024-09-22T20:06:15.693+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:06:15.691+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/new_dag.py
[2024-09-22T20:06:15.714+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:06:15.709+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/new_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/new_dag.py", line 4, in <module>
    from profile_task.test_oop import DataAgregation
ModuleNotFoundError: No module named 'profile_task'
[2024-09-22T20:06:15.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/new_dag.py
[2024-09-22T20:06:15.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/new_dag.py took 0.065 seconds
[2024-09-22T20:06:46.078+0000] {processor.py:186} INFO - Started process (PID=48) to work on /opt/airflow/dags/new_dag.py
[2024-09-22T20:06:46.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/new_dag.py for tasks to queue
[2024-09-22T20:06:46.083+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:06:46.083+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/new_dag.py
[2024-09-22T20:06:46.100+0000] {logging_mixin.py:190} INFO - [2024-09-22T20:06:46.097+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/new_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/new_dag.py", line 4, in <module>
    from profile_task.test_oop import DataAgregation
ModuleNotFoundError: No module named 'profile_task'
[2024-09-22T20:06:46.102+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/new_dag.py
[2024-09-22T20:06:46.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/new_dag.py took 0.050 seconds
